# Задание 1 Работа со списками (list)

Напишите программу, которая считывает с клавиатуры размер списка целых чисел. От 1 до размера списка сгенерировать случайным образом (random) массив.

Вывести для сгенерированного массива:
* длину
* последний элемент
* массив в обратном порядке (реверс)
* если массив содержит числа 5 и 17 вывести “Да”, иначе “Нет”
* создать копию массива и у копии удалить первый и последний элементы (использовать pop)

**Выход программы:**

Введите размер массива: 20

Длина массива: 20

Последний элемент массива: 74

Массив в обратном порядке: 74, 35, 59, 100, 29, 65, 58, 91, 40, 96, 36, 80, 66, 72, 77, 75, 76, 98, 90, 35

Нет

Копия массива после удаления первого и последнего элементов: 90, 98, 76, 75, 77, 72, 66, 80, 36, 96, 40, 91, 58, 65, 29, 100, 59, 35


In [4]:
import random


# Метод получения результата по "Задание 1 Работа со списками (list)"
def getResult(array):
    length = len(array)
    lastElem = array[len(array) - 1]
    containElem5And17 = contain5And17(array)
    copyArray = delateFstAndLstElemOfCopy(array)
    reversArray = reverse(array, 0, len(array) - 1)

    return (f"Длина массива: {length}\n"
            f"Последний элемент массива: {lastElem}\n"
            f"Массив в обратном порядке: {reversArray}\n"
            f"{containElem5And17}\n"
            f"Копия массива после удаления первого и последнего элементов: {copyArray}")


# Метод разворачивающий массив в обратном порядке
def reverse(arr, left, right):
    while left < right:
        temp = arr[left]
        arr[left] = arr[right]
        arr[right] = temp
        left += 1
        right -= 1
    return arr


# Метод, определеяющий содержание в массиве чисел 5 и 17
def contain5And17(array):
    contains5 = 5 in array
    contains7 = 17 in array
    if contains5 and contains7:
        return "Да"
    else:
        return "Нет"


# Метод копирующий входной массив и удаляющий у него первый и последний элемент
def delateFstAndLstElemOfCopy(array):
    result = array.copy()
    result.pop(0)
    result.pop(len(result) - 1)
    return result


n = int(input("Введите размер массива: "))
array = [random.randint(1, n) for number in range(n)]
output = getResult(array)
print(output)

Длина массива: 10
Последний элемент массива: 3
Массив в обратном порядке: [3, 2, 6, 8, 1, 8, 7, 9, 3, 9]
Нет
Копия массива после удаления первого и последнего элементов: [3, 9, 7, 8, 1, 8, 6, 2]


# Задание 2 Работа с кортежами (tuples)


Напишите программу, которая преобразует введенный пользователем список целых чисел в кортеж. Затем программа должна вычислить и вывести:
* среднее значение
* минимальное значение
* максимальное значение значение

всех чисел в кортеже.


**Вход программы:**

Введите числа, разделенные пробелами: 4 2 3 5 7 8 4 6 5 2 44 22 11 55 77 88

**Выход программы:**

Среднее значение: 21.438

Минимальное значение: 2

Максимальное значение: 88


In [5]:
# Метод получения результата по "Задание 2 Работа с кортежами (tuples)"
def getAnswer(array):
    tuple = convert(array)
    averageValue = getAverageValue(tuple)
    maxElement = getMaxValue(tuple)
    minElement = getMinValue(tuple)
    return (f"Среднее значение: {averageValue}\n"
            f"Минимальное значение: {minElement}\n"
            f"Максимальное значение: {maxElement}")


# Метод конвертирующий массив целых чисел в кортеж
def convert(array):
    return tuple(array)


# Метод получения среднего значения
def getAverageValue(array):
    n = len(array)
    total = 0
    for element in array:
        total += element
    return total / n


# Метод получения минимального значения
def getMinValue(array):
    min = array[0]
    for element in array:
        if element < min:
            min = element
    return min


# Метод получения максимального значения
def getMaxValue(array):
    max = array[0]
    for element in array:
        if element > max:
            max = element
    return max


array = list(map(int, input("Введите числа, разделенные пробелами: ").split()))
output = getAnswer(array)
print(output)

Среднее значение: 5.5
Минимальное значение: 1
Максимальное значение: 10


# Задание 3 Работа с матрицей NumPy


На вход программе подается список натуральных чисел, разделенных пробелом. После ввода убедиться, что чисел хватает для создания квадратной матрицы.


Необходимо:
* сформировать двумерный квадратный массив numpy (квадратную матрицу), последовательно располагая элементы списка по строкам матрицы
* вывести на экран через пробел диагональные элементы полученного двумерного массива.

**Вход программы:**

Введите числа, разделенные пробелом: 2 3 1 5 3 8 7 16 17

**Выход программы:**

Квадратная матрица:
 [[ 2  3  1]
 [ 5  3  8]
 [ 7 16 17]]

Диагональные элементы: 2 3 17

**Вход программы:**

Введите числа, разделенные пробелом: 2 3 1 5 3 8 7

**Выход программы:**

Ошибка: чисел не хватит для квадратной матрицы.


In [6]:
import numpy as np


# Метод возвращающий квадратную матрицу и ее диагональные элементы
def getSquareMatrixAndDiagonal(arr):
    if abilityCreateSquareMatrix(arr):
        size = int(len(arr) ** 0.5)
        squareMatrix = np.array(arr).reshape(size, size)
        # Если необходим вывод квадратной матрицы в одну строку (как в примере к задаче)
        # squareMatrix = [list(x) for x in zip(*squareMatrix)]
        if abilityGetDiagonalElements(squareMatrix):
            diagonalElements = np.array(squareMatrix).diagonal()
            return (f'Квадратная матрица:\n{squareMatrix}\n'
                    f'Диагональные элементы: {diagonalElements}')
        else:
            return (f'Квадратная матрица: {squareMatrix}\n'
                    f'Для получения диагональных элементов требуется матрица, как минимум из двух измерений.')
    else:
        return "Чисел не хватит для квадратной матрицы."


# Метод проверяющий возможность создания квадратной матрицы из входного массива
def abilityCreateSquareMatrix(arr):
    size = len(arr) ** 0.5
    if size % 1 == 0:
        return True
    else:
        return False


# Метод проверяющий возможность получения диагональных элементов (т.к при одном измерении это не возможно)
def abilityGetDiagonalElements(arr):
    rows = arr.shape[0]
    if rows > 1:
        return True
    else:
        return False


array = list(map(int, input("Введите числа, разделенные пробелом: ").split()))
output = getSquareMatrixAndDiagonal(array)
print(output)

Квадратная матрица:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Диагональные элементы: [ 1  6 11 16]


# Задание 4 Срезы и операции с матрицами NumPy


Дана матрица из 4-х строк. Выполнить с матрицей следующие действия:

1. Из исходной матрицы сделать две новые матрицы. Первая будет состоять из первых двух строк исходной матрицы, вторая - из оставшихся строк. Распечатать полученные матрицы.
2. Посчитать сумму полученных в п.1 двух матриц. Посчитать среднее значение получившейся матрицы суммы. Распечатать полученные значения.
3. Посчитать разность полученных в п.1 двух матриц. Посчитать среднее значение получившейся матрицы разности. Распечатать полученные значения.
4. Вывести на экран произведение средних для матрицы суммы и разности.



In [7]:
import numpy as np


# Метод получения результата по "Задание 4 Срезы и операции с матрицами NumPy"
def getAnswer(matrix):
    print(f"Исходная матрица:\n{matrix}\n")

    newMatrices = np.split(matrix, 2)
    matrix1 = newMatrices[0]
    matrix2 = newMatrices[1]
    print(f"Матрица 1:\n{matrix1}\n"
          f"Матрица 2:\n{matrix2}\n")

    matrixSum = matrix1 + matrix2
    print("Матрица после сложения 1 и 2 части:\n", matrixSum)

    averageValueOfSum = np.mean(matrixSum)
    print(f"Среднее значение суммы матриц: {averageValueOfSum}\n")

    matrixDifference = matrix1 - matrix2
    print("Матрица после вычитания 1 и 2 части:\n", matrixDifference)

    averageValueOfDifference = np.mean(matrixDifference)
    print(f"Среднее значение вычитания матриц: {averageValueOfDifference}\n")

    print(f"Произведение средних значений: {averageValueOfSum * averageValueOfDifference}")


matrix = np.random.randint(1, 10, (4, 4))
getAnswer(matrix)


Исходная матрица:
[[6 9 1 4]
 [6 5 8 7]
 [2 9 7 2]
 [7 2 5 4]]

Матрица 1:
[[6 9 1 4]
 [6 5 8 7]]
Матрица 2:
[[2 9 7 2]
 [7 2 5 4]]

Матрица после сложения 1 и 2 части:
 [[ 8 18  8  6]
 [13  7 13 11]]
Среднее значение суммы матриц: 10.5

Матрица после вычитания 1 и 2 части:
 [[ 4  0 -6  2]
 [-1  3  3  3]]
Среднее значение вычитания матриц: 1.0

Произведение средних значений: 10.5
